(cl:in-package race_car_pkg-msg)
(cl:export '(UX_MPS-VAL
          UX_MPS
          UY_MPS-VAL
          UY_MPS
          R_RADPS-VAL
          R_RADPS
          AX_MPS2-VAL
          AX_MPS2
          AY_MPS2-VAL
          AY_MPS2
          SPEED_RPM-VAL
          SPEED_RPM
          DELTA_RAD-VAL
          DELTA_RAD
          SINGLE_MOTOR_TXR_NM-VAL
          SINGLE_MOTOR_TXR_NM
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          ROLL_RAD-VAL
          ROLL_RAD
          PITCH_RAD-VAL
          PITCH_RAD
          YAW_RAD-VAL
          YAW_RAD
          GPS_STATE-VAL
          GPS_STATE
          UWB_X_M-VAL
          UWB_X_M
          UWB_Y_M-VAL
          UWB_Y_M
          EKF_X_M-VAL
          EKF_X_M
          EKF_Y_M-VAL
          EKF_Y_M
))