(cl:in-package in2ulv_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VIN-VAL
          VIN
          CURRENT_STOP-VAL
          CURRENT_STOP
          ROUTE_STOP-VAL
          ROUTE_STOP
          ROUTE_LINE-VAL
          ROUTE_LINE
          CONTROL_MODE-VAL
          CONTROL_MODE
          VEH_STATUS-VAL
          VEH_STATUS
          GPS_VEH-VAL
          GPS_VEH
          GPS_STOP-VAL
          GPS_STOP
          TRIP_DISTANCE-VAL
          TRIP_DISTANCE
          TRIP_ETA-VAL
          TRIP_ETA
          TRIP_LEFT_MILEAGE-VAL
          TRIP_LEFT_MILEAGE
          SYSPOWMODE-VAL
          SYSPOWMODE
          HZRDLTIO-VAL
          HZRDLTIO
          WINDSCENWIPST-VAL
          WINDSCENWIPST
          HIGHBEEM-VAL
          HIGHBEEM
          LOWBEEM-VAL
          LOWBEEM
          WINDOWS-VAL
          WINDOWS
          DOORLOCK-VAL
          DOORLOCK
          DOORSWITCH-VAL
          DOORSWITCH
          EMERGENCYBUTTON-VAL
          EMERGENCYBUTTON
          SPEED-VAL
          SPEED
          ANGLE-VAL
          ANGLE
          SOC-VAL
          SOC
          EVENT-VAL
          EVENT
))