(cl:in-package in2ulv_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MODULE_TYPE-VAL
          MODULE_TYPE
          ERROR_CODE-VAL
          ERROR_CODE
          UCU_VALIDITY-VAL
          UCU_VALIDITY
          ROUTE_ENCODER-VAL
          ROUTE_ENCODER
          VERSION-VAL
          VERSION
          PROVINCE-VAL
          PROVINCE
          CITY-VAL
          CITY
          DISTRICT-VAL
          DISTRICT
          STREET-VAL
          STREET
          COMMUNITY-VAL
          COMMUNITY
          FEATUREREQUEST-VAL
          FEATUREREQUEST
          CARHEADING-VAL
          CARHEADING
          XXTYPE-VAL
          XXTYPE
          MAPNUMBER-VAL
          MAPNUMBER
          STATIONNUMBER-VAL
          STATIONNUMBER
          REMOTECTRLCOMMAND-VAL
          REMOTECTRLCOMMAND
))