(cl:in-package in2ulv_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TRAJECTORY_POINT_X-VAL
          TRAJECTORY_POINT_X
          TRAJECTORY_POINT_Y-VAL
          TRAJECTORY_POINT_Y
          TRAJECTORY_POINT_THETA-VAL
          TRAJECTORY_POINT_THETA
          TRAJECTORY_POINT_KAPPA-VAL
          TRAJECTORY_POINT_KAPPA
          TRAJECTORY_POINT_V-VAL
          TRAJECTORY_POINT_V
          TRAJECTORY_POINT_A-VAL
          TRAJECTORY_POINT_A
          MATCHED_POINT_S-VAL
          MATCHED_POINT_S
          MATCHED_POINT_X-VAL
          MATCHED_POINT_X
          MATCHED_POINT_Y-VAL
          MATCHED_POINT_Y
          MATCHED_POINT_THETA-VAL
          MATCHED_POINT_THETA
          MATCHED_POINT_KAPPA-VAL
          MATCHED_POINT_KAPPA
          MATCHED_POINT_KAPPA_PRIME-VAL
          MATCHED_POINT_KAPPA_PRIME
          S-VAL
          S
          S_DOT-VAL
          S_DOT
          S_DDOT-VAL
          S_DDOT
          D-VAL
          D
          D_PRIME-VAL
          D_PRIME
          D_PPRIME-VAL
          D_PPRIME
          STOP_POINT_DISTANCE-VAL
          STOP_POINT_DISTANCE
))