(cl:in-package in2ulv_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          STEER-VAL
          STEER
          BRAKE-VAL
          BRAKE
          IF_BRAKE-VAL
          IF_BRAKE
          SPEED_CONTROL-VAL
          SPEED_CONTROL
          IF_SPEED-VAL
          IF_SPEED
          ACCELERATION_CONTROL-VAL
          ACCELERATION_CONTROL
          IF_ACCELERATION-VAL
          IF_ACCELERATION
          IS_LEFT_LIGHTING-VAL
          IS_LEFT_LIGHTING
          IS_RIGHT_LIGHTING-VAL
          IS_RIGHT_LIGHTING
          IS_HOOK_CLOSE-VAL
          IS_HOOK_CLOSE
          HOOK_POSITION-VAL
          HOOK_POSITION
          GEAR_INFO-VAL
          GEAR_INFO
          SPEED_LIMIT-VAL
          SPEED_LIMIT
          SPEED_OUT-VAL
          SPEED_OUT
))