(cl:in-package in2ulv_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MODULE_TYPE-VAL
          MODULE_TYPE
          ERROR_CODE-VAL
          ERROR_CODE
          INS_DATA-VAL
          INS_DATA
          IMU-VAL
          IMU
          NAV_SAT_FIX-VAL
          NAV_SAT_FIX
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          INS_PITCHANGLE-VAL
          INS_PITCHANGLE
          INS_ROLLANGLE-VAL
          INS_ROLLANGLE
          INS_HEADINGANGLE-VAL
          INS_HEADINGANGLE
          INS_LOCATHEIGHT-VAL
          INS_LOCATHEIGHT
          INS_TIME-VAL
          INS_TIME
          INS_LATITUDE-VAL
          INS_LATITUDE
          INS_LONGITUDE-VAL
          INS_LONGITUDE
          INS_NORTHSPD-VAL
          INS_NORTHSPD
          INS_EASTSPD-VAL
          INS_EASTSPD
          INS_TOGROUNDSPD-VAL
          INS_TOGROUNDSPD
          INS_GPSFLAG_POS-VAL
          INS_GPSFLAG_POS
          INS_NUMSV-VAL
          INS_NUMSV
          INS_GPSFLAG_HEADING-VAL
          INS_GPSFLAG_HEADING
          INS_GPS_AGE-VAL
          INS_GPS_AGE
          INS_CAR_STATUS-VAL
          INS_CAR_STATUS
          INS_STATUS-VAL
          INS_STATUS
          INS_STD_LAT-VAL
          INS_STD_LAT
          INS_STD_LON-VAL
          INS_STD_LON
          INS_STD_LOCATHEIGHT-VAL
          INS_STD_LOCATHEIGHT
          INS_STD_HEADING-VAL
          INS_STD_HEADING
          INS_UTM_EAST-VAL
          INS_UTM_EAST
          INS_UTM_NORTH-VAL
          INS_UTM_NORTH
          INS_UTM_NORTHSPD-VAL
          INS_UTM_NORTHSPD
          INS_UTM_EASTSPD-VAL
          INS_UTM_EASTSPD
))