// Generated by gencpp from file in2ulv_msgs/ActionType.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_ACTIONTYPE_H
#define IN2ULV_MSGS_MESSAGE_ACTIONTYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct ActionType_
{
  typedef ActionType_<ContainerAllocator> Type;

  ActionType_()
    : header()
    , mode_type(0)
    , action_type(0)
    , task_type(0)
    , target_point()
    , veh_status(0)  {
    }
  ActionType_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode_type(0)
    , action_type(0)
    , task_type(0)
    , target_point(_alloc)
    , veh_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_type_type;
  _mode_type_type mode_type;

   typedef uint8_t _action_type_type;
  _action_type_type action_type;

   typedef uint8_t _task_type_type;
  _task_type_type task_type;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _target_point_type;
  _target_point_type target_point;

   typedef uint16_t _veh_status_type;
  _veh_status_type veh_status;





  typedef boost::shared_ptr< ::in2ulv_msgs::ActionType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::ActionType_<ContainerAllocator> const> ConstPtr;

}; // struct ActionType_

typedef ::in2ulv_msgs::ActionType_<std::allocator<void> > ActionType;

typedef boost::shared_ptr< ::in2ulv_msgs::ActionType > ActionTypePtr;
typedef boost::shared_ptr< ::in2ulv_msgs::ActionType const> ActionTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::ActionType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::ActionType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::ActionType_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::ActionType_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode_type == rhs.mode_type &&
    lhs.action_type == rhs.action_type &&
    lhs.task_type == rhs.task_type &&
    lhs.target_point == rhs.target_point &&
    lhs.veh_status == rhs.veh_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::ActionType_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::ActionType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::ActionType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::ActionType_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::ActionType_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49541e196c68da7c6efd757fb7bb50aa";
  }

  static const char* value(const ::in2ulv_msgs::ActionType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49541e196c68da7cULL;
  static const uint64_t static_value2 = 0x6efd757fb7bb50aaULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/ActionType";
  }

  static const char* value(const ::in2ulv_msgs::ActionType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# ULV模式\n"
"uint8 mode_type\n"
"\n"
"# 动作类型\n"
"uint8 action_type\n"
"\n"
"# 线路类型\n"
"uint8 task_type\n"
"\n"
"# 目标点\n"
"geometry_msgs/Point target_point\n"
"\n"
"uint16 veh_status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::in2ulv_msgs::ActionType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode_type);
      stream.next(m.action_type);
      stream.next(m.task_type);
      stream.next(m.target_point);
      stream.next(m.veh_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::ActionType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::ActionType_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode_type);
    s << indent << "action_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action_type);
    s << indent << "task_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_type);
    s << indent << "target_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.target_point);
    s << indent << "veh_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.veh_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_ACTIONTYPE_H
