// Generated by gencpp from file in2ulv_msgs/CheckWithinLaneletRequest.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELETREQUEST_H
#define IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct CheckWithinLaneletRequest_
{
  typedef CheckWithinLaneletRequest_<ContainerAllocator> Type;

  CheckWithinLaneletRequest_()
    : header()
    , use_localization_result(false)
    , position()  {
    }
  CheckWithinLaneletRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , use_localization_result(false)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _use_localization_result_type;
  _use_localization_result_type use_localization_result;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckWithinLaneletRequest_

typedef ::in2ulv_msgs::CheckWithinLaneletRequest_<std::allocator<void> > CheckWithinLaneletRequest;

typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletRequest > CheckWithinLaneletRequestPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletRequest const> CheckWithinLaneletRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.use_localization_result == rhs.use_localization_result &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10e3ea31a0a17a13a6a3dd0876eaa675";
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10e3ea31a0a17a13ULL;
  static const uint64_t static_value2 = 0xa6a3dd0876eaa675ULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/CheckWithinLaneletRequest";
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# 是否将当前定位结果作为目标点位置\n"
"bool use_localization_result\n"
"\n"
"# use_localization_result 为 false 时候，需要设置目标点位置\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.use_localization_result);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckWithinLaneletRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::CheckWithinLaneletRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "use_localization_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_localization_result);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELETREQUEST_H
