// Generated by gencpp from file in2ulv_msgs/CheckWithinLaneletResponse.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELETRESPONSE_H
#define IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct CheckWithinLaneletResponse_
{
  typedef CheckWithinLaneletResponse_<ContainerAllocator> Type;

  CheckWithinLaneletResponse_()
    : within(false)  {
    }
  CheckWithinLaneletResponse_(const ContainerAllocator& _alloc)
    : within(false)  {
  (void)_alloc;
    }



   typedef uint8_t _within_type;
  _within_type within;





  typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckWithinLaneletResponse_

typedef ::in2ulv_msgs::CheckWithinLaneletResponse_<std::allocator<void> > CheckWithinLaneletResponse;

typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletResponse > CheckWithinLaneletResponsePtr;
typedef boost::shared_ptr< ::in2ulv_msgs::CheckWithinLaneletResponse const> CheckWithinLaneletResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator2> & rhs)
{
  return lhs.within == rhs.within;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c26375269acff67a6df61904ced4a03d";
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc26375269acff67aULL;
  static const uint64_t static_value2 = 0x6df61904ced4a03dULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/CheckWithinLaneletResponse";
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 是否在 lanelet 上\n"
"bool within\n"
;
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.within);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckWithinLaneletResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::CheckWithinLaneletResponse_<ContainerAllocator>& v)
  {
    s << indent << "within: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.within);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELETRESPONSE_H
