// Generated by gencpp from file in2ulv_msgs/CheckWithinLanelet.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELET_H
#define IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELET_H

#include <ros/service_traits.h>


#include <in2ulv_msgs/CheckWithinLaneletRequest.h>
#include <in2ulv_msgs/CheckWithinLaneletResponse.h>


namespace in2ulv_msgs
{

struct CheckWithinLanelet
{

typedef CheckWithinLaneletRequest Request;
typedef CheckWithinLaneletResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckWithinLanelet
} // namespace in2ulv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::in2ulv_msgs::CheckWithinLanelet > {
  static const char* value()
  {
    return "da164720bf0d4371b7d840e959c11d6e";
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLanelet&) { return value(); }
};

template<>
struct DataType< ::in2ulv_msgs::CheckWithinLanelet > {
  static const char* value()
  {
    return "in2ulv_msgs/CheckWithinLanelet";
  }

  static const char* value(const ::in2ulv_msgs::CheckWithinLanelet&) { return value(); }
};


// service_traits::MD5Sum< ::in2ulv_msgs::CheckWithinLaneletRequest> should match
// service_traits::MD5Sum< ::in2ulv_msgs::CheckWithinLanelet >
template<>
struct MD5Sum< ::in2ulv_msgs::CheckWithinLaneletRequest>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::CheckWithinLanelet >::value();
  }
  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::CheckWithinLaneletRequest> should match
// service_traits::DataType< ::in2ulv_msgs::CheckWithinLanelet >
template<>
struct DataType< ::in2ulv_msgs::CheckWithinLaneletRequest>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::CheckWithinLanelet >::value();
  }
  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::in2ulv_msgs::CheckWithinLaneletResponse> should match
// service_traits::MD5Sum< ::in2ulv_msgs::CheckWithinLanelet >
template<>
struct MD5Sum< ::in2ulv_msgs::CheckWithinLaneletResponse>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::CheckWithinLanelet >::value();
  }
  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::CheckWithinLaneletResponse> should match
// service_traits::DataType< ::in2ulv_msgs::CheckWithinLanelet >
template<>
struct DataType< ::in2ulv_msgs::CheckWithinLaneletResponse>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::CheckWithinLanelet >::value();
  }
  static const char* value(const ::in2ulv_msgs::CheckWithinLaneletResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_CHECKWITHINLANELET_H
