// Generated by gencpp from file in2ulv_msgs/DrivingInfo.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_DRIVINGINFO_H
#define IN2ULV_MSGS_MESSAGE_DRIVINGINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct DrivingInfo_
{
  typedef DrivingInfo_<ContainerAllocator> Type;

  DrivingInfo_()
    : header()
    , avoidanceflag(false)
    , total_mileage(0.0)
    , completed_mileage(0.0)
    , remaining_time(0.0)  {
    }
  DrivingInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , avoidanceflag(false)
    , total_mileage(0.0)
    , completed_mileage(0.0)
    , remaining_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _avoidanceflag_type;
  _avoidanceflag_type avoidanceflag;

   typedef double _total_mileage_type;
  _total_mileage_type total_mileage;

   typedef double _completed_mileage_type;
  _completed_mileage_type completed_mileage;

   typedef double _remaining_time_type;
  _remaining_time_type remaining_time;





  typedef boost::shared_ptr< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> const> ConstPtr;

}; // struct DrivingInfo_

typedef ::in2ulv_msgs::DrivingInfo_<std::allocator<void> > DrivingInfo;

typedef boost::shared_ptr< ::in2ulv_msgs::DrivingInfo > DrivingInfoPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::DrivingInfo const> DrivingInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.avoidanceflag == rhs.avoidanceflag &&
    lhs.total_mileage == rhs.total_mileage &&
    lhs.completed_mileage == rhs.completed_mileage &&
    lhs.remaining_time == rhs.remaining_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fdabca3408297c4e235a4ea8aa8aad5";
  }

  static const char* value(const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fdabca3408297c4ULL;
  static const uint64_t static_value2 = 0xe235a4ea8aa8aad5ULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/DrivingInfo";
  }

  static const char* value(const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"bool avoidanceflag\n"
"\n"
"float64 total_mileage\n"
"\n"
"float64 completed_mileage\n"
"\n"
"float64 remaining_time\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.avoidanceflag);
      stream.next(m.total_mileage);
      stream.next(m.completed_mileage);
      stream.next(m.remaining_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrivingInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::DrivingInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::DrivingInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "avoidanceflag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.avoidanceflag);
    s << indent << "total_mileage: ";
    Printer<double>::stream(s, indent + "  ", v.total_mileage);
    s << indent << "completed_mileage: ";
    Printer<double>::stream(s, indent + "  ", v.completed_mileage);
    s << indent << "remaining_time: ";
    Printer<double>::stream(s, indent + "  ", v.remaining_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_DRIVINGINFO_H
