// Generated by gencpp from file in2ulv_msgs/GetNextStationRequest.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_GETNEXTSTATIONREQUEST_H
#define IN2ULV_MSGS_MESSAGE_GETNEXTSTATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct GetNextStationRequest_
{
  typedef GetNextStationRequest_<ContainerAllocator> Type;

  GetNextStationRequest_()
    : header()
    , station_positions()  {
    }
  GetNextStationRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , station_positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _station_positions_type;
  _station_positions_type station_positions;





  typedef boost::shared_ptr< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetNextStationRequest_

typedef ::in2ulv_msgs::GetNextStationRequest_<std::allocator<void> > GetNextStationRequest;

typedef boost::shared_ptr< ::in2ulv_msgs::GetNextStationRequest > GetNextStationRequestPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::GetNextStationRequest const> GetNextStationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.station_positions == rhs.station_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ed6156e11995c558d9db36bba9f96ae";
  }

  static const char* value(const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ed6156e11995c55ULL;
  static const uint64_t static_value2 = 0x8d9db36bba9f96aeULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/GetNextStationRequest";
  }

  static const char* value(const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# 站点位置\n"
"geometry_msgs/Point[] station_positions\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.station_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNextStationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::GetNextStationRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "station_positions[]" << std::endl;
    for (size_t i = 0; i < v.station_positions.size(); ++i)
    {
      s << indent << "  station_positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.station_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_GETNEXTSTATIONREQUEST_H
