// Generated by gencpp from file in2ulv_msgs/GetNextStation.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_GETNEXTSTATION_H
#define IN2ULV_MSGS_MESSAGE_GETNEXTSTATION_H

#include <ros/service_traits.h>


#include <in2ulv_msgs/GetNextStationRequest.h>
#include <in2ulv_msgs/GetNextStationResponse.h>


namespace in2ulv_msgs
{

struct GetNextStation
{

typedef GetNextStationRequest Request;
typedef GetNextStationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNextStation
} // namespace in2ulv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::in2ulv_msgs::GetNextStation > {
  static const char* value()
  {
    return "6913a9d233b1fe0b71190001ea6fea24";
  }

  static const char* value(const ::in2ulv_msgs::GetNextStation&) { return value(); }
};

template<>
struct DataType< ::in2ulv_msgs::GetNextStation > {
  static const char* value()
  {
    return "in2ulv_msgs/GetNextStation";
  }

  static const char* value(const ::in2ulv_msgs::GetNextStation&) { return value(); }
};


// service_traits::MD5Sum< ::in2ulv_msgs::GetNextStationRequest> should match
// service_traits::MD5Sum< ::in2ulv_msgs::GetNextStation >
template<>
struct MD5Sum< ::in2ulv_msgs::GetNextStationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::GetNextStation >::value();
  }
  static const char* value(const ::in2ulv_msgs::GetNextStationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::GetNextStationRequest> should match
// service_traits::DataType< ::in2ulv_msgs::GetNextStation >
template<>
struct DataType< ::in2ulv_msgs::GetNextStationRequest>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::GetNextStation >::value();
  }
  static const char* value(const ::in2ulv_msgs::GetNextStationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::in2ulv_msgs::GetNextStationResponse> should match
// service_traits::MD5Sum< ::in2ulv_msgs::GetNextStation >
template<>
struct MD5Sum< ::in2ulv_msgs::GetNextStationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::GetNextStation >::value();
  }
  static const char* value(const ::in2ulv_msgs::GetNextStationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::GetNextStationResponse> should match
// service_traits::DataType< ::in2ulv_msgs::GetNextStation >
template<>
struct DataType< ::in2ulv_msgs::GetNextStationResponse>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::GetNextStation >::value();
  }
  static const char* value(const ::in2ulv_msgs::GetNextStationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_GETNEXTSTATION_H
