// Generated by gencpp from file in2ulv_msgs/HMIModeCommandRequest.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_HMIMODECOMMANDREQUEST_H
#define IN2ULV_MSGS_MESSAGE_HMIMODECOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct HMIModeCommandRequest_
{
  typedef HMIModeCommandRequest_<ContainerAllocator> Type;

  HMIModeCommandRequest_()
    : header()
    , mode_type(0)  {
    }
  HMIModeCommandRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode_type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_type_type;
  _mode_type_type mode_type;





  typedef boost::shared_ptr< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HMIModeCommandRequest_

typedef ::in2ulv_msgs::HMIModeCommandRequest_<std::allocator<void> > HMIModeCommandRequest;

typedef boost::shared_ptr< ::in2ulv_msgs::HMIModeCommandRequest > HMIModeCommandRequestPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::HMIModeCommandRequest const> HMIModeCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode_type == rhs.mode_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2076c5a9de23a7c0d34019916302d207";
  }

  static const char* value(const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2076c5a9de23a7c0ULL;
  static const uint64_t static_value2 = 0xd34019916302d207ULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/HMIModeCommandRequest";
  }

  static const char* value(const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# 模式设置\n"
"uint8 mode_type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HMIModeCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::HMIModeCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_HMIMODECOMMANDREQUEST_H
