// Generated by gencpp from file in2ulv_msgs/HMIModeCommand.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_HMIMODECOMMAND_H
#define IN2ULV_MSGS_MESSAGE_HMIMODECOMMAND_H

#include <ros/service_traits.h>


#include <in2ulv_msgs/HMIModeCommandRequest.h>
#include <in2ulv_msgs/HMIModeCommandResponse.h>


namespace in2ulv_msgs
{

struct HMIModeCommand
{

typedef HMIModeCommandRequest Request;
typedef HMIModeCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HMIModeCommand
} // namespace in2ulv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::in2ulv_msgs::HMIModeCommand > {
  static const char* value()
  {
    return "faa5d2d67ab17bd67adc93c419a58b77";
  }

  static const char* value(const ::in2ulv_msgs::HMIModeCommand&) { return value(); }
};

template<>
struct DataType< ::in2ulv_msgs::HMIModeCommand > {
  static const char* value()
  {
    return "in2ulv_msgs/HMIModeCommand";
  }

  static const char* value(const ::in2ulv_msgs::HMIModeCommand&) { return value(); }
};


// service_traits::MD5Sum< ::in2ulv_msgs::HMIModeCommandRequest> should match
// service_traits::MD5Sum< ::in2ulv_msgs::HMIModeCommand >
template<>
struct MD5Sum< ::in2ulv_msgs::HMIModeCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::HMIModeCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMIModeCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::HMIModeCommandRequest> should match
// service_traits::DataType< ::in2ulv_msgs::HMIModeCommand >
template<>
struct DataType< ::in2ulv_msgs::HMIModeCommandRequest>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::HMIModeCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMIModeCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::in2ulv_msgs::HMIModeCommandResponse> should match
// service_traits::MD5Sum< ::in2ulv_msgs::HMIModeCommand >
template<>
struct MD5Sum< ::in2ulv_msgs::HMIModeCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::HMIModeCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMIModeCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::HMIModeCommandResponse> should match
// service_traits::DataType< ::in2ulv_msgs::HMIModeCommand >
template<>
struct DataType< ::in2ulv_msgs::HMIModeCommandResponse>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::HMIModeCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMIModeCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_HMIMODECOMMAND_H
