// Generated by gencpp from file in2ulv_msgs/HMISettingCommand.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_HMISETTINGCOMMAND_H
#define IN2ULV_MSGS_MESSAGE_HMISETTINGCOMMAND_H

#include <ros/service_traits.h>


#include <in2ulv_msgs/HMISettingCommandRequest.h>
#include <in2ulv_msgs/HMISettingCommandResponse.h>


namespace in2ulv_msgs
{

struct HMISettingCommand
{

typedef HMISettingCommandRequest Request;
typedef HMISettingCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HMISettingCommand
} // namespace in2ulv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::in2ulv_msgs::HMISettingCommand > {
  static const char* value()
  {
    return "77df7fba1f2ff481f39b2e6000b80ae0";
  }

  static const char* value(const ::in2ulv_msgs::HMISettingCommand&) { return value(); }
};

template<>
struct DataType< ::in2ulv_msgs::HMISettingCommand > {
  static const char* value()
  {
    return "in2ulv_msgs/HMISettingCommand";
  }

  static const char* value(const ::in2ulv_msgs::HMISettingCommand&) { return value(); }
};


// service_traits::MD5Sum< ::in2ulv_msgs::HMISettingCommandRequest> should match
// service_traits::MD5Sum< ::in2ulv_msgs::HMISettingCommand >
template<>
struct MD5Sum< ::in2ulv_msgs::HMISettingCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::HMISettingCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMISettingCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::HMISettingCommandRequest> should match
// service_traits::DataType< ::in2ulv_msgs::HMISettingCommand >
template<>
struct DataType< ::in2ulv_msgs::HMISettingCommandRequest>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::HMISettingCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMISettingCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::in2ulv_msgs::HMISettingCommandResponse> should match
// service_traits::MD5Sum< ::in2ulv_msgs::HMISettingCommand >
template<>
struct MD5Sum< ::in2ulv_msgs::HMISettingCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::in2ulv_msgs::HMISettingCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMISettingCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::in2ulv_msgs::HMISettingCommandResponse> should match
// service_traits::DataType< ::in2ulv_msgs::HMISettingCommand >
template<>
struct DataType< ::in2ulv_msgs::HMISettingCommandResponse>
{
  static const char* value()
  {
    return DataType< ::in2ulv_msgs::HMISettingCommand >::value();
  }
  static const char* value(const ::in2ulv_msgs::HMISettingCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_HMISETTINGCOMMAND_H
