// Generated by gencpp from file in2ulv_msgs/HMIStepReport.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_HMISTEPREPORT_H
#define IN2ULV_MSGS_MESSAGE_HMISTEPREPORT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct HMIStepReport_
{
  typedef HMIStepReport_<ContainerAllocator> Type;

  HMIStepReport_()
    : header()
    , step_report(0)
    , station_id(0)  {
    }
  HMIStepReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , step_report(0)
    , station_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _step_report_type;
  _step_report_type step_report;

   typedef uint32_t _station_id_type;
  _station_id_type station_id;





  typedef boost::shared_ptr< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> const> ConstPtr;

}; // struct HMIStepReport_

typedef ::in2ulv_msgs::HMIStepReport_<std::allocator<void> > HMIStepReport;

typedef boost::shared_ptr< ::in2ulv_msgs::HMIStepReport > HMIStepReportPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::HMIStepReport const> HMIStepReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.step_report == rhs.step_report &&
    lhs.station_id == rhs.station_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1690f2b8b61886c2a07014ccb5c01a39";
  }

  static const char* value(const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1690f2b8b61886c2ULL;
  static const uint64_t static_value2 = 0xa07014ccb5c01a39ULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/HMIStepReport";
  }

  static const char* value(const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# 任务步骤反馈\n"
"# FULL_SUCCESS 或 PART_SUCCESS\n"
"uint8 step_report\n"
"\n"
"# 如果完成的是带有 station id 的 HEAD_FOR_GOAL 任务，则返回正确的 station id\n"
"uint32 station_id\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.step_report);
      stream.next(m.station_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HMIStepReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::HMIStepReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::HMIStepReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "step_report: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.step_report);
    s << indent << "station_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.station_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_HMISTEPREPORT_H
