// Generated by gencpp from file in2ulv_msgs/HookMsg.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_HOOKMSG_H
#define IN2ULV_MSGS_MESSAGE_HOOKMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct HookMsg_
{
  typedef HookMsg_<ContainerAllocator> Type;

  HookMsg_()
    : header()
    , module_type(0)
    , error_code(0)
    , AHDCortSts(0)
    , HokPosVal(0)
    , HokCntpintSts(0)
    , HokCntSts(0)
    , HokRstSts(0)  {
    }
  HookMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , module_type(0)
    , error_code(0)
    , AHDCortSts(0)
    , HokPosVal(0)
    , HokCntpintSts(0)
    , HokCntSts(0)
    , HokRstSts(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _module_type_type;
  _module_type_type module_type;

   typedef uint32_t _error_code_type;
  _error_code_type error_code;

   typedef uint8_t _AHDCortSts_type;
  _AHDCortSts_type AHDCortSts;

   typedef int32_t _HokPosVal_type;
  _HokPosVal_type HokPosVal;

   typedef uint8_t _HokCntpintSts_type;
  _HokCntpintSts_type HokCntpintSts;

   typedef uint8_t _HokCntSts_type;
  _HokCntSts_type HokCntSts;

   typedef uint8_t _HokRstSts_type;
  _HokRstSts_type HokRstSts;





  typedef boost::shared_ptr< ::in2ulv_msgs::HookMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::HookMsg_<ContainerAllocator> const> ConstPtr;

}; // struct HookMsg_

typedef ::in2ulv_msgs::HookMsg_<std::allocator<void> > HookMsg;

typedef boost::shared_ptr< ::in2ulv_msgs::HookMsg > HookMsgPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::HookMsg const> HookMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::HookMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::HookMsg_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HookMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.module_type == rhs.module_type &&
    lhs.error_code == rhs.error_code &&
    lhs.AHDCortSts == rhs.AHDCortSts &&
    lhs.HokPosVal == rhs.HokPosVal &&
    lhs.HokCntpintSts == rhs.HokCntpintSts &&
    lhs.HokCntSts == rhs.HokCntSts &&
    lhs.HokRstSts == rhs.HokRstSts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::HookMsg_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HookMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HookMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HookMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HookMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5d852e0489802c930a6ca6cba9f4263";
  }

  static const char* value(const ::in2ulv_msgs::HookMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5d852e0489802c9ULL;
  static const uint64_t static_value2 = 0x30a6ca6cba9f4263ULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/HookMsg";
  }

  static const char* value(const ::in2ulv_msgs::HookMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# 模块类型\n"
"uint8 module_type\n"
"\n"
"# error_code\n"
"uint32 error_code\n"
"\n"
"# 模块信息\n"
"# AHD General Status 0x340\n"
"uint8 AHDCortSts    # 自动脱挂钩纠偏状态\n"
"int32 HokPosVal     # 挂钩位置\n"
"uint8 HokCntpintSts # 挂钩对位状态\n"
"uint8 HokCntSts     # 挂钩连接状态\n"
"uint8 HokRstSts     # 挂钩复位状态\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::in2ulv_msgs::HookMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.module_type);
      stream.next(m.error_code);
      stream.next(m.AHDCortSts);
      stream.next(m.HokPosVal);
      stream.next(m.HokCntpintSts);
      stream.next(m.HokCntSts);
      stream.next(m.HokRstSts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HookMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::HookMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::HookMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "module_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.module_type);
    s << indent << "error_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "AHDCortSts: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AHDCortSts);
    s << indent << "HokPosVal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.HokPosVal);
    s << indent << "HokCntpintSts: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HokCntpintSts);
    s << indent << "HokCntSts: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HokCntSts);
    s << indent << "HokRstSts: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HokRstSts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_HOOKMSG_H
