// Generated by gencpp from file in2ulv_msgs/HookCtrlMsg.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_HOOKCTRLMSG_H
#define IN2ULV_MSGS_MESSAGE_HOOKCTRLMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct HookCtrlMsg_
{
  typedef HookCtrlMsg_<ContainerAllocator> Type;

  HookCtrlMsg_()
    : header()
    , module_type(0)
    , error_code(0)
    , AHDModRqst(0)
    , BckUpSts(0)
    , AHDRstRqst(0)
    , AHDPosRqstV(0)
    , AHDPosRqst(0)  {
    }
  HookCtrlMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , module_type(0)
    , error_code(0)
    , AHDModRqst(0)
    , BckUpSts(0)
    , AHDRstRqst(0)
    , AHDPosRqstV(0)
    , AHDPosRqst(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _module_type_type;
  _module_type_type module_type;

   typedef uint32_t _error_code_type;
  _error_code_type error_code;

   typedef uint8_t _AHDModRqst_type;
  _AHDModRqst_type AHDModRqst;

   typedef uint8_t _BckUpSts_type;
  _BckUpSts_type BckUpSts;

   typedef uint8_t _AHDRstRqst_type;
  _AHDRstRqst_type AHDRstRqst;

   typedef uint8_t _AHDPosRqstV_type;
  _AHDPosRqstV_type AHDPosRqstV;

   typedef int32_t _AHDPosRqst_type;
  _AHDPosRqst_type AHDPosRqst;





  typedef boost::shared_ptr< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> const> ConstPtr;

}; // struct HookCtrlMsg_

typedef ::in2ulv_msgs::HookCtrlMsg_<std::allocator<void> > HookCtrlMsg;

typedef boost::shared_ptr< ::in2ulv_msgs::HookCtrlMsg > HookCtrlMsgPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::HookCtrlMsg const> HookCtrlMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.module_type == rhs.module_type &&
    lhs.error_code == rhs.error_code &&
    lhs.AHDModRqst == rhs.AHDModRqst &&
    lhs.BckUpSts == rhs.BckUpSts &&
    lhs.AHDRstRqst == rhs.AHDRstRqst &&
    lhs.AHDPosRqstV == rhs.AHDPosRqstV &&
    lhs.AHDPosRqst == rhs.AHDPosRqst;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9051bf82eb1b0bc832bea74601287bfd";
  }

  static const char* value(const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9051bf82eb1b0bc8ULL;
  static const uint64_t static_value2 = 0x32bea74601287bfdULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/HookCtrlMsg";
  }

  static const char* value(const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# 模块类型\n"
"uint8 module_type\n"
"\n"
"# error_code\n"
"uint32 error_code\n"
"\n"
"# 模块信息\n"
"# IDU Automatic Hook Status 0x31E\n"
"uint8 AHDModRqst    # 自动脱挂钩功能请求\n"
"uint8 BckUpSts      # 倒车状态\n"
"uint8 AHDRstRqst    # 自动脱挂钩重置请求\n"
"uint8 AHDPosRqstV   # 自动脱挂钩位置请求有效性\n"
"int32 AHDPosRqst    # 自动脱挂钩位置请求\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.module_type);
      stream.next(m.error_code);
      stream.next(m.AHDModRqst);
      stream.next(m.BckUpSts);
      stream.next(m.AHDRstRqst);
      stream.next(m.AHDPosRqstV);
      stream.next(m.AHDPosRqst);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HookCtrlMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::HookCtrlMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "module_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.module_type);
    s << indent << "error_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "AHDModRqst: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AHDModRqst);
    s << indent << "BckUpSts: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BckUpSts);
    s << indent << "AHDRstRqst: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AHDRstRqst);
    s << indent << "AHDPosRqstV: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AHDPosRqstV);
    s << indent << "AHDPosRqst: ";
    Printer<int32_t>::stream(s, indent + "  ", v.AHDPosRqst);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_HOOKCTRLMSG_H
