// Generated by gencpp from file in2ulv_msgs/INSStdMsg.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_INSSTDMSG_H
#define IN2ULV_MSGS_MESSAGE_INSSTDMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Imu.h>
#include <sensor_msgs/NavSatFix.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct INSStdMsg_
{
  typedef INSStdMsg_<ContainerAllocator> Type;

  INSStdMsg_()
    : header()
    , module_type(0)
    , error_code(0)
    , ins_data()
    , imu()
    , nav_sat_fix()
    , ACC_X(0.0)
    , ACC_Y(0.0)
    , ACC_Z(0.0)
    , GYRO_X(0.0)
    , GYRO_Y(0.0)
    , GYRO_Z(0.0)
    , INS_PitchAngle(0.0)
    , INS_RollAngle(0.0)
    , INS_HeadingAngle(0.0)
    , INS_LocatHeight(0.0)
    , INS_Time(0)
    , INS_Latitude(0.0)
    , INS_Longitude(0.0)
    , INS_NorthSpd(0.0)
    , INS_EastSpd(0.0)
    , INS_ToGroundSpd(0.0)
    , INS_GpsFlag_Pos(0)
    , INS_NumSV(0)
    , INS_GpsFlag_Heading(0)
    , INS_Gps_Age(0)
    , INS_Car_Status(0)
    , INS_Status(0)
    , INS_Std_Lat(0.0)
    , INS_Std_Lon(0.0)
    , INS_Std_LocatHeight(0.0)
    , INS_Std_Heading(0.0)
    , INS_UTM_East(0.0)
    , INS_UTM_North(0.0)
    , INS_UTM_NorthSpd(0.0)
    , INS_UTM_EastSpd(0.0)  {
    }
  INSStdMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , module_type(0)
    , error_code(0)
    , ins_data(_alloc)
    , imu(_alloc)
    , nav_sat_fix(_alloc)
    , ACC_X(0.0)
    , ACC_Y(0.0)
    , ACC_Z(0.0)
    , GYRO_X(0.0)
    , GYRO_Y(0.0)
    , GYRO_Z(0.0)
    , INS_PitchAngle(0.0)
    , INS_RollAngle(0.0)
    , INS_HeadingAngle(0.0)
    , INS_LocatHeight(0.0)
    , INS_Time(0)
    , INS_Latitude(0.0)
    , INS_Longitude(0.0)
    , INS_NorthSpd(0.0)
    , INS_EastSpd(0.0)
    , INS_ToGroundSpd(0.0)
    , INS_GpsFlag_Pos(0)
    , INS_NumSV(0)
    , INS_GpsFlag_Heading(0)
    , INS_Gps_Age(0)
    , INS_Car_Status(0)
    , INS_Status(0)
    , INS_Std_Lat(0.0)
    , INS_Std_Lon(0.0)
    , INS_Std_LocatHeight(0.0)
    , INS_Std_Heading(0.0)
    , INS_UTM_East(0.0)
    , INS_UTM_North(0.0)
    , INS_UTM_NorthSpd(0.0)
    , INS_UTM_EastSpd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _module_type_type;
  _module_type_type module_type;

   typedef uint32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ins_data_type;
  _ins_data_type ins_data;

   typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _imu_type;
  _imu_type imu;

   typedef  ::sensor_msgs::NavSatFix_<ContainerAllocator>  _nav_sat_fix_type;
  _nav_sat_fix_type nav_sat_fix;

   typedef double _ACC_X_type;
  _ACC_X_type ACC_X;

   typedef double _ACC_Y_type;
  _ACC_Y_type ACC_Y;

   typedef double _ACC_Z_type;
  _ACC_Z_type ACC_Z;

   typedef double _GYRO_X_type;
  _GYRO_X_type GYRO_X;

   typedef double _GYRO_Y_type;
  _GYRO_Y_type GYRO_Y;

   typedef double _GYRO_Z_type;
  _GYRO_Z_type GYRO_Z;

   typedef double _INS_PitchAngle_type;
  _INS_PitchAngle_type INS_PitchAngle;

   typedef double _INS_RollAngle_type;
  _INS_RollAngle_type INS_RollAngle;

   typedef double _INS_HeadingAngle_type;
  _INS_HeadingAngle_type INS_HeadingAngle;

   typedef double _INS_LocatHeight_type;
  _INS_LocatHeight_type INS_LocatHeight;

   typedef uint32_t _INS_Time_type;
  _INS_Time_type INS_Time;

   typedef double _INS_Latitude_type;
  _INS_Latitude_type INS_Latitude;

   typedef double _INS_Longitude_type;
  _INS_Longitude_type INS_Longitude;

   typedef double _INS_NorthSpd_type;
  _INS_NorthSpd_type INS_NorthSpd;

   typedef double _INS_EastSpd_type;
  _INS_EastSpd_type INS_EastSpd;

   typedef double _INS_ToGroundSpd_type;
  _INS_ToGroundSpd_type INS_ToGroundSpd;

   typedef uint8_t _INS_GpsFlag_Pos_type;
  _INS_GpsFlag_Pos_type INS_GpsFlag_Pos;

   typedef uint8_t _INS_NumSV_type;
  _INS_NumSV_type INS_NumSV;

   typedef uint8_t _INS_GpsFlag_Heading_type;
  _INS_GpsFlag_Heading_type INS_GpsFlag_Heading;

   typedef uint8_t _INS_Gps_Age_type;
  _INS_Gps_Age_type INS_Gps_Age;

   typedef uint8_t _INS_Car_Status_type;
  _INS_Car_Status_type INS_Car_Status;

   typedef uint8_t _INS_Status_type;
  _INS_Status_type INS_Status;

   typedef float _INS_Std_Lat_type;
  _INS_Std_Lat_type INS_Std_Lat;

   typedef float _INS_Std_Lon_type;
  _INS_Std_Lon_type INS_Std_Lon;

   typedef float _INS_Std_LocatHeight_type;
  _INS_Std_LocatHeight_type INS_Std_LocatHeight;

   typedef float _INS_Std_Heading_type;
  _INS_Std_Heading_type INS_Std_Heading;

   typedef double _INS_UTM_East_type;
  _INS_UTM_East_type INS_UTM_East;

   typedef double _INS_UTM_North_type;
  _INS_UTM_North_type INS_UTM_North;

   typedef double _INS_UTM_NorthSpd_type;
  _INS_UTM_NorthSpd_type INS_UTM_NorthSpd;

   typedef double _INS_UTM_EastSpd_type;
  _INS_UTM_EastSpd_type INS_UTM_EastSpd;





  typedef boost::shared_ptr< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> const> ConstPtr;

}; // struct INSStdMsg_

typedef ::in2ulv_msgs::INSStdMsg_<std::allocator<void> > INSStdMsg;

typedef boost::shared_ptr< ::in2ulv_msgs::INSStdMsg > INSStdMsgPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::INSStdMsg const> INSStdMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.module_type == rhs.module_type &&
    lhs.error_code == rhs.error_code &&
    lhs.ins_data == rhs.ins_data &&
    lhs.imu == rhs.imu &&
    lhs.nav_sat_fix == rhs.nav_sat_fix &&
    lhs.ACC_X == rhs.ACC_X &&
    lhs.ACC_Y == rhs.ACC_Y &&
    lhs.ACC_Z == rhs.ACC_Z &&
    lhs.GYRO_X == rhs.GYRO_X &&
    lhs.GYRO_Y == rhs.GYRO_Y &&
    lhs.GYRO_Z == rhs.GYRO_Z &&
    lhs.INS_PitchAngle == rhs.INS_PitchAngle &&
    lhs.INS_RollAngle == rhs.INS_RollAngle &&
    lhs.INS_HeadingAngle == rhs.INS_HeadingAngle &&
    lhs.INS_LocatHeight == rhs.INS_LocatHeight &&
    lhs.INS_Time == rhs.INS_Time &&
    lhs.INS_Latitude == rhs.INS_Latitude &&
    lhs.INS_Longitude == rhs.INS_Longitude &&
    lhs.INS_NorthSpd == rhs.INS_NorthSpd &&
    lhs.INS_EastSpd == rhs.INS_EastSpd &&
    lhs.INS_ToGroundSpd == rhs.INS_ToGroundSpd &&
    lhs.INS_GpsFlag_Pos == rhs.INS_GpsFlag_Pos &&
    lhs.INS_NumSV == rhs.INS_NumSV &&
    lhs.INS_GpsFlag_Heading == rhs.INS_GpsFlag_Heading &&
    lhs.INS_Gps_Age == rhs.INS_Gps_Age &&
    lhs.INS_Car_Status == rhs.INS_Car_Status &&
    lhs.INS_Status == rhs.INS_Status &&
    lhs.INS_Std_Lat == rhs.INS_Std_Lat &&
    lhs.INS_Std_Lon == rhs.INS_Std_Lon &&
    lhs.INS_Std_LocatHeight == rhs.INS_Std_LocatHeight &&
    lhs.INS_Std_Heading == rhs.INS_Std_Heading &&
    lhs.INS_UTM_East == rhs.INS_UTM_East &&
    lhs.INS_UTM_North == rhs.INS_UTM_North &&
    lhs.INS_UTM_NorthSpd == rhs.INS_UTM_NorthSpd &&
    lhs.INS_UTM_EastSpd == rhs.INS_UTM_EastSpd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e660d7b5d497967dad824f69729739ae";
  }

  static const char* value(const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe660d7b5d497967dULL;
  static const uint64_t static_value2 = 0xad824f69729739aeULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/INSStdMsg";
  }

  static const char* value(const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 帧头，包含时间戳信息\n"
"std_msgs/Header header\n"
"\n"
"# 模块类型\n"
"uint8 module_type\n"
"\n"
"# error_code\n"
"uint32 error_code\n"
"\n"
"# 模块信息\n"
"string ins_data\n"
"\n"
"# ROS 标准信息\n"
"sensor_msgs/Imu imu\n"
"sensor_msgs/NavSatFix nav_sat_fix\n"
"\n"
"# INS_Acc (0X500)\n"
"float64 ACC_X\n"
"float64 ACC_Y\n"
"float64 ACC_Z\n"
"\n"
"# INS_GYRO (0X501)\n"
"float64 GYRO_X\n"
"float64 GYRO_Y\n"
"float64 GYRO_Z\n"
"\n"
"# INS_HeadingPitchRoll (0X502)\n"
"float64 INS_PitchAngle\n"
"float64 INS_RollAngle\n"
"float64 INS_HeadingAngle\n"
"\n"
"# INS_HeightAndTime (0X503)\n"
"float64 INS_LocatHeight\n"
"uint32 INS_Time\n"
"\n"
"# INS_LatitudeLongitude (0X504)\n"
"float64 INS_Latitude\n"
"float64 INS_Longitude\n"
"\n"
"# INS_Speed (0X505)\n"
"float64 INS_NorthSpd\n"
"float64 INS_EastSpd\n"
"float64 INS_ToGroundSpd\n"
"\n"
"# INS_DataInfo (0X506)\n"
"uint8 INS_GpsFlag_Pos\n"
"uint8 INS_NumSV     #星数\n"
"uint8 INS_GpsFlag_Heading\n"
"uint8 INS_Gps_Age\n"
"uint8 INS_Car_Status\n"
"uint8 INS_Status\n"
"\n"
"# INS_Std (0X507)\n"
"float32 INS_Std_Lat\n"
"float32 INS_Std_Lon\n"
"float32 INS_Std_LocatHeight\n"
"float32 INS_Std_Heading\n"
"\n"
"# 新增的 UTM 坐标字段\n"
"float64 INS_UTM_East\n"
"float64 INS_UTM_North\n"
"float64 INS_UTM_NorthSpd\n"
"float64 INS_UTM_EastSpd\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Imu\n"
"# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"#\n"
"# If the covariance of the measurement is known, it should be filled in (if all you know is the \n"
"# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n"
"# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n"
"# data a covariance will have to be assumed or gotten from some other source\n"
"#\n"
"# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n"
"# estimate), please set element 0 of the associated covariance matrix to -1\n"
"# If you are interpreting this message, please check for a value of -1 in the first element of each \n"
"# covariance matrix, and disregard the associated estimate.\n"
"\n"
"Header header\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"float64[9] orientation_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"float64[9] angular_velocity_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"float64[9] linear_acceleration_covariance # Row major x, y z \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatFix\n"
"# Navigation Satellite fix for any Global Navigation Satellite System\n"
"#\n"
"# Specified using the WGS 84 reference ellipsoid\n"
"\n"
"# header.stamp specifies the ROS time for this measurement (the\n"
"#        corresponding satellite time may be reported using the\n"
"#        sensor_msgs/TimeReference message).\n"
"#\n"
"# header.frame_id is the frame of reference reported by the satellite\n"
"#        receiver, usually the location of the antenna.  This is a\n"
"#        Euclidean frame relative to the vehicle, not a reference\n"
"#        ellipsoid.\n"
"Header header\n"
"\n"
"# satellite fix status information\n"
"NavSatStatus status\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south.\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is west.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid\n"
"# (quiet NaN if no altitude is available).\n"
"float64 altitude\n"
"\n"
"# Position covariance [m^2] defined relative to a tangential plane\n"
"# through the reported position. The components are East, North, and\n"
"# Up (ENU), in row-major order.\n"
"#\n"
"# Beware: this coordinate system exhibits singularities at the poles.\n"
"\n"
"float64[9] position_covariance\n"
"\n"
"# If the covariance of the fix is known, fill it in completely. If the\n"
"# GPS receiver provides the variance of each measurement, put them\n"
"# along the diagonal. If only Dilution of Precision is available,\n"
"# estimate an approximate covariance from that.\n"
"\n"
"uint8 COVARIANCE_TYPE_UNKNOWN = 0\n"
"uint8 COVARIANCE_TYPE_APPROXIMATED = 1\n"
"uint8 COVARIANCE_TYPE_DIAGONAL_KNOWN = 2\n"
"uint8 COVARIANCE_TYPE_KNOWN = 3\n"
"\n"
"uint8 position_covariance_type\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatStatus\n"
"# Navigation Satellite fix status for any Global Navigation Satellite System\n"
"\n"
"# Whether to output an augmented fix is determined by both the fix\n"
"# type and the last time differential corrections were received.  A\n"
"# fix is valid when status >= STATUS_FIX.\n"
"\n"
"int8 STATUS_NO_FIX =  -1        # unable to fix position\n"
"int8 STATUS_FIX =      0        # unaugmented fix\n"
"int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation\n"
"int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation\n"
"\n"
"int8 status\n"
"\n"
"# Bits defining which Global Navigation Satellite System signals were\n"
"# used by the receiver.\n"
"\n"
"uint16 SERVICE_GPS =     1\n"
"uint16 SERVICE_GLONASS = 2\n"
"uint16 SERVICE_COMPASS = 4      # includes BeiDou.\n"
"uint16 SERVICE_GALILEO = 8\n"
"\n"
"uint16 service\n"
;
  }

  static const char* value(const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.module_type);
      stream.next(m.error_code);
      stream.next(m.ins_data);
      stream.next(m.imu);
      stream.next(m.nav_sat_fix);
      stream.next(m.ACC_X);
      stream.next(m.ACC_Y);
      stream.next(m.ACC_Z);
      stream.next(m.GYRO_X);
      stream.next(m.GYRO_Y);
      stream.next(m.GYRO_Z);
      stream.next(m.INS_PitchAngle);
      stream.next(m.INS_RollAngle);
      stream.next(m.INS_HeadingAngle);
      stream.next(m.INS_LocatHeight);
      stream.next(m.INS_Time);
      stream.next(m.INS_Latitude);
      stream.next(m.INS_Longitude);
      stream.next(m.INS_NorthSpd);
      stream.next(m.INS_EastSpd);
      stream.next(m.INS_ToGroundSpd);
      stream.next(m.INS_GpsFlag_Pos);
      stream.next(m.INS_NumSV);
      stream.next(m.INS_GpsFlag_Heading);
      stream.next(m.INS_Gps_Age);
      stream.next(m.INS_Car_Status);
      stream.next(m.INS_Status);
      stream.next(m.INS_Std_Lat);
      stream.next(m.INS_Std_Lon);
      stream.next(m.INS_Std_LocatHeight);
      stream.next(m.INS_Std_Heading);
      stream.next(m.INS_UTM_East);
      stream.next(m.INS_UTM_North);
      stream.next(m.INS_UTM_NorthSpd);
      stream.next(m.INS_UTM_EastSpd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct INSStdMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::INSStdMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::INSStdMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "module_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.module_type);
    s << indent << "error_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "ins_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ins_data);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
    s << indent << "nav_sat_fix: ";
    s << std::endl;
    Printer< ::sensor_msgs::NavSatFix_<ContainerAllocator> >::stream(s, indent + "  ", v.nav_sat_fix);
    s << indent << "ACC_X: ";
    Printer<double>::stream(s, indent + "  ", v.ACC_X);
    s << indent << "ACC_Y: ";
    Printer<double>::stream(s, indent + "  ", v.ACC_Y);
    s << indent << "ACC_Z: ";
    Printer<double>::stream(s, indent + "  ", v.ACC_Z);
    s << indent << "GYRO_X: ";
    Printer<double>::stream(s, indent + "  ", v.GYRO_X);
    s << indent << "GYRO_Y: ";
    Printer<double>::stream(s, indent + "  ", v.GYRO_Y);
    s << indent << "GYRO_Z: ";
    Printer<double>::stream(s, indent + "  ", v.GYRO_Z);
    s << indent << "INS_PitchAngle: ";
    Printer<double>::stream(s, indent + "  ", v.INS_PitchAngle);
    s << indent << "INS_RollAngle: ";
    Printer<double>::stream(s, indent + "  ", v.INS_RollAngle);
    s << indent << "INS_HeadingAngle: ";
    Printer<double>::stream(s, indent + "  ", v.INS_HeadingAngle);
    s << indent << "INS_LocatHeight: ";
    Printer<double>::stream(s, indent + "  ", v.INS_LocatHeight);
    s << indent << "INS_Time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.INS_Time);
    s << indent << "INS_Latitude: ";
    Printer<double>::stream(s, indent + "  ", v.INS_Latitude);
    s << indent << "INS_Longitude: ";
    Printer<double>::stream(s, indent + "  ", v.INS_Longitude);
    s << indent << "INS_NorthSpd: ";
    Printer<double>::stream(s, indent + "  ", v.INS_NorthSpd);
    s << indent << "INS_EastSpd: ";
    Printer<double>::stream(s, indent + "  ", v.INS_EastSpd);
    s << indent << "INS_ToGroundSpd: ";
    Printer<double>::stream(s, indent + "  ", v.INS_ToGroundSpd);
    s << indent << "INS_GpsFlag_Pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_GpsFlag_Pos);
    s << indent << "INS_NumSV: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_NumSV);
    s << indent << "INS_GpsFlag_Heading: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_GpsFlag_Heading);
    s << indent << "INS_Gps_Age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_Gps_Age);
    s << indent << "INS_Car_Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_Car_Status);
    s << indent << "INS_Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_Status);
    s << indent << "INS_Std_Lat: ";
    Printer<float>::stream(s, indent + "  ", v.INS_Std_Lat);
    s << indent << "INS_Std_Lon: ";
    Printer<float>::stream(s, indent + "  ", v.INS_Std_Lon);
    s << indent << "INS_Std_LocatHeight: ";
    Printer<float>::stream(s, indent + "  ", v.INS_Std_LocatHeight);
    s << indent << "INS_Std_Heading: ";
    Printer<float>::stream(s, indent + "  ", v.INS_Std_Heading);
    s << indent << "INS_UTM_East: ";
    Printer<double>::stream(s, indent + "  ", v.INS_UTM_East);
    s << indent << "INS_UTM_North: ";
    Printer<double>::stream(s, indent + "  ", v.INS_UTM_North);
    s << indent << "INS_UTM_NorthSpd: ";
    Printer<double>::stream(s, indent + "  ", v.INS_UTM_NorthSpd);
    s << indent << "INS_UTM_EastSpd: ";
    Printer<double>::stream(s, indent + "  ", v.INS_UTM_EastSpd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_INSSTDMSG_H
