// Generated by gencpp from file in2ulv_msgs/LocationsInfo.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_LOCATIONSINFO_H
#define IN2ULV_MSGS_MESSAGE_LOCATIONSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct LocationsInfo_
{
  typedef LocationsInfo_<ContainerAllocator> Type;

  LocationsInfo_()
    : header()
    , position()
    , attitude()  {
    }
  LocationsInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , attitude(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _attitude_type;
  _attitude_type attitude;





  typedef boost::shared_ptr< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> const> ConstPtr;

}; // struct LocationsInfo_

typedef ::in2ulv_msgs::LocationsInfo_<std::allocator<void> > LocationsInfo;

typedef boost::shared_ptr< ::in2ulv_msgs::LocationsInfo > LocationsInfoPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::LocationsInfo const> LocationsInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.attitude == rhs.attitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1689f33734d547e34a281a134b06547f";
  }

  static const char* value(const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1689f33734d547e3ULL;
  static const uint64_t static_value2 = 0x4a281a134b06547fULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/LocationsInfo";
  }

  static const char* value(const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"#位置信息\n"
"geometry_msgs/Vector3 position\n"
"#姿态信息\n"
"geometry_msgs/Vector3 attitude\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.attitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocationsInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::LocationsInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::LocationsInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "attitude: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_LOCATIONSINFO_H
