// Generated by gencpp from file in2ulv_msgs/SignalInfo.msg
// DO NOT EDIT!


#ifndef IN2ULV_MSGS_MESSAGE_SIGNALINFO_H
#define IN2ULV_MSGS_MESSAGE_SIGNALINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace in2ulv_msgs
{
template <class ContainerAllocator>
struct SignalInfo_
{
  typedef SignalInfo_<ContainerAllocator> Type;

  SignalInfo_()
    : header()
    , signal(false)  {
    }
  SignalInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signal(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _signal_type;
  _signal_type signal;





  typedef boost::shared_ptr< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SignalInfo_

typedef ::in2ulv_msgs::SignalInfo_<std::allocator<void> > SignalInfo;

typedef boost::shared_ptr< ::in2ulv_msgs::SignalInfo > SignalInfoPtr;
typedef boost::shared_ptr< ::in2ulv_msgs::SignalInfo const> SignalInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::in2ulv_msgs::SignalInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::in2ulv_msgs::SignalInfo_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::SignalInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signal == rhs.signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::in2ulv_msgs::SignalInfo_<ContainerAllocator1> & lhs, const ::in2ulv_msgs::SignalInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace in2ulv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70f6c980fd9a5a13a4ccaf5fb3adefdd";
  }

  static const char* value(const ::in2ulv_msgs::SignalInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70f6c980fd9a5a13ULL;
  static const uint64_t static_value2 = 0xa4ccaf5fb3adefddULL;
};

template<class ContainerAllocator>
struct DataType< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "in2ulv_msgs/SignalInfo";
  }

  static const char* value(const ::in2ulv_msgs::SignalInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"#交通灯信号 0为绿灯 1为红灯\n"
"bool signal\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::in2ulv_msgs::SignalInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SignalInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::in2ulv_msgs::SignalInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::in2ulv_msgs::SignalInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IN2ULV_MSGS_MESSAGE_SIGNALINFO_H
