# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from in2ulv_msgs/GisInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class GisInfo(genpy.Message):
  _md5sum = "c9625dbf880cccfdb88400ff3cfa664d"
  _type = "in2ulv_msgs/GisInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
#行驶模式标志,0停止，1行驶
uint8 status
#转向灯,0不闪，1右转向灯闪，2左转向灯闪
uint8 indicator_status
#档位，0空挡，1为D档，2为R档，3为P档
uint8 gear
#GIS局部路径导航点，输出原点为（1500，1000）
float64[301] x
float64[301] y
#-PI左偏到PI右偏
float64[301] yaw
#对应导航点期望速度
float64[301] speed


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','status','indicator_status','gear','x','y','yaw','speed']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','float64[301]','float64[301]','float64[301]','float64[301]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,status,indicator_status,gear,x,y,yaw,speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GisInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.status is None:
        self.status = 0
      if self.indicator_status is None:
        self.indicator_status = 0
      if self.gear is None:
        self.gear = 0
      if self.x is None:
        self.x = [0.] * 301
      if self.y is None:
        self.y = [0.] * 301
      if self.yaw is None:
        self.yaw = [0.] * 301
      if self.speed is None:
        self.speed = [0.] * 301
    else:
      self.header = std_msgs.msg.Header()
      self.status = 0
      self.indicator_status = 0
      self.gear = 0
      self.x = [0.] * 301
      self.y = [0.] * 301
      self.yaw = [0.] * 301
      self.speed = [0.] * 301

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.status, _x.indicator_status, _x.gear))
      buff.write(_get_struct_301d().pack(*self.x))
      buff.write(_get_struct_301d().pack(*self.y))
      buff.write(_get_struct_301d().pack(*self.yaw))
      buff.write(_get_struct_301d().pack(*self.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.status, _x.indicator_status, _x.gear,) = _get_struct_3B().unpack(str[start:end])
      start = end
      end += 2408
      self.x = _get_struct_301d().unpack(str[start:end])
      start = end
      end += 2408
      self.y = _get_struct_301d().unpack(str[start:end])
      start = end
      end += 2408
      self.yaw = _get_struct_301d().unpack(str[start:end])
      start = end
      end += 2408
      self.speed = _get_struct_301d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.status, _x.indicator_status, _x.gear))
      buff.write(self.x.tostring())
      buff.write(self.y.tostring())
      buff.write(self.yaw.tostring())
      buff.write(self.speed.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.status, _x.indicator_status, _x.gear,) = _get_struct_3B().unpack(str[start:end])
      start = end
      end += 2408
      self.x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=301)
      start = end
      end += 2408
      self.y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=301)
      start = end
      end += 2408
      self.yaw = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=301)
      start = end
      end += 2408
      self.speed = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=301)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_301d = None
def _get_struct_301d():
    global _struct_301d
    if _struct_301d is None:
        _struct_301d = struct.Struct("<301d")
    return _struct_301d
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
