(cl:defpackage in2ulv_msgs-srv
  (:use )
  (:export
   "HMIMODECOMMAND"
   "<HMIMODECOMMAND-REQUEST>"
   "HMIMODECOMMAND-REQUEST"
   "<HMIMODECOMMAND-RESPONSE>"
   "HMIMODECOMMAND-RESPONSE"
   "HMISETTINGCOMMAND"
   "<HMISETTINGCOMMAND-REQUEST>"
   "HMISETTINGCOMMAND-REQUEST"
   "<HMISETTINGCOMMAND-RESPONSE>"
   "HMISETTINGCOMMAND-RESPONSE"
  ))

